hello: Hello (default profile)

# multiple profiles in yaml, or use multiple files, e.g.: configs-dev.yml
---
spring.profiles: dev
hello: Hello (dev profile)
---
spring.profiles: test
hello: Hello (test profile)

